# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e103072068da917ecc7b656624e0bd52472e7ee91b28eff3a004c5300e9299332bbea7fb50b77832dbb69aa4f957023173cba13df21e43bc63c1920aef847b18

test:
  secret_key_base: 09a986d41dc7dc52d018511b90b9cadc9d65208548819d4cccebcafb5ce41b3c42aa4ca9c9dcbc5d0db1c788d7b22f8e46351c984004fc55fdf0a23b085ed4df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
